### ISSUE TITLE
The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections'

### ISSUE THREAD

**Issue by kreys** [IvanMurzak/Unity-MCP#160]
Hello,

I'm installing your package following all the instructions, however in the last step after installing package, there are compilation errors in unity about not knowing 'Immutable' type.

`Library/PackageCache/com.ivanmurzak.unity.mcp@f0176c4d3b41/Server/Common/Runner/Resource/Content/RunResourceContext.cs(4,26): error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?)`

`Library/PackageCache/com.ivanmurzak.unity.mcp@f0176c4d3b41/Server/Common/Runner/Resource/List/RunResourceContent.cs(4,26): error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?)`

Immutable package is already installed from dependencies, I've tried all the solutions I could think of, checked bot .NET Standard 2.1 and Framework versions.

I tried to resolve these errors first on local copy of your package, so I copied the whole package directory to Assets, installed manually all the dependencies. What is interesting, there were no compilation error with this package as local one - everything compiles nice and clear, AI connector window shows up and there are only errors and warning about not using this package as local installation.

Any ideas how to fix the Immutable types when using your package as external package?

Unity 6000.2.0b7
MacBook Pro 16 M1 (Apple silicon)
MacOS Sequoia 15.5

**Comment by IvanMurzak** [comment]
Hi @kreys , thanks for the reports. It looks like the error of latest update. I will fix it. 

For now, please try to roll back to the version 0.8.3.

**Comment by kreys** [comment]
Ok, after rolling back to 0.8.3 exact same errors shows up:

`Library/PackageCache/com.ivanmurzak.unity.mcp@d990a26ce42f/Server/Common/Runner/Resource/Content/RunResourceContext.cs(4,26): error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?)`
`Library/PackageCache/com.ivanmurzak.unity.mcp@d990a26ce42f/Server/Common/Runner/Resource/List/RunResourceContent.cs(4,26): error CS0234: The type or namespace name 'Immutable' does not exist in the namespace 'System.Collections' (are you missing an assembly reference?)`

I've tried doing exactly the same steps on windows machine, with the same Unity (6000.2.0b7) and on the windows machine there are no errors, and AI Connection window shows up.

**Comment by kreys** [comment]
The newest version that compiles properly is 0.7.5, however it throws a lot of warnings about missing meta files:

<img width="1050" height="379" alt="Image" src="https://github.com/user-attachments/assets/a74d58d7-6058-4c0e-9f7a-c235f9696178" />

**Comment by IvanMurzak** [comment]
Ahha, please try to install dotnet 9.0 and dotnet asp.net 9.0 for Mac arm.

If that helps I will add these instructions to README

**Comment by kreys** [comment]
Ok, installing asp.net didn't change anything concerning compilation errors.

However, I've opened the project with stable Unity 6000.0.43f1 (Mac Apple Silicon) and there are no compilation errors, I've also managed to setup proper MCP connection. 

I've also downloaded newest beta (Unity 6000.2.0b8) and suddenly it works. I've looked on the Release Notes of that build, and there is one mention about "Immutable" packages, maybe that fixes my issue as well:

Editor: Fixed "Immutable Packages" warning thrown after changing platform to Linux. ([UUM-97876](https://issuetracker.unity3d.com/issues/the-following-asset-s-located-in-immutable-packages-were-unexpectedly-altered-warning-is-thrown-after-changing-platform-to-linux))

TLDR:
It works on newest Unity 6000.2.0b8.

**Comment by IvanMurzak** [comment]
@kreys could you please check the latest update `0.11.0`? It assume the issue should be resolved already.

**Comment by IvanMurzak** [comment]
Seems like this issue is related: https://github.com/IvanMurzak/Unity-MCP/issues/142

**Comment by IvanMurzak** [comment]
It is fixed in one of the latest updates.

**Comment by semateos** [comment]
This issue persists in 0.41.0, Unity 6.3, Macbook M1 Pro, .NET

**Comment by IvanMurzak** [comment]
> This issue persists in 0.41.0, Unity 6.3, Macbook M1 Pro, .NET

Thanks for the report. It was fixed in the 0.41.1, check it out. Please let me know if the issue still exists in the update.
