### ISSUE TITLE
error after upgrading to 0.69

### ISSUE THREAD

**Issue by akbarjahangiri** [IvanMurzak/Unity-MCP#723]
Library\PackageCache\com.ivanmurzak.unity.mcp@3d4d4707112d\Editor\Scripts\API\Tool\Assets.Shader.GetData.cs(111,53): error CS1519: Invalid token '{' in class, record, struct, or interface member declaration

**Comment by IvanMurzak** [comment]
This is a duplicate issue:
https://github.com/IvanMurzak/Unity-MCP/issues/721
