### ISSUE TITLE
ViewQuery Errors After Update to 0.67.1

### ISSUE THREAD

**Issue by vaulcul** [IvanMurzak/Unity-MCP#699]
After updating from v0.66.1 to v0.67.1 I'm given the following errors, VS Studio2026 shows no errors, but Unity does:

Library\PackageCache\com.ivanmurzak.unity.mcp@79b09d5f9af4\Editor\Scripts\API\Tool\Assets.GetData.cs(55,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@79b09d5f9af4\Editor\Scripts\API\Tool\Object.GetData.cs(55,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@79b09d5f9af4\Editor\Scripts\API\Tool\Assets.Shader.GetData.cs(66,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@79b09d5f9af4\Editor\Scripts\API\Tool\GameObject.Component.Get.pre-Unity.6.5.cs(65,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@79b09d5f9af4\Editor\Scripts\API\Tool\Scene.GetData.cs(60,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@79b09d5f9af4\Editor\Scripts\API\Tool\GameObject.Find.cs(68,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

**Comment by IvanMurzak** [comment]
@vaulcul please try to force `Tools` / `AI Game Developer` / `Dependencies` / `Force Resolve NuGet DLLs` in Unity Editor.

<img width="955" height="399" alt="Image" src="https://github.com/user-attachments/assets/00de7f0b-5d8f-45a8-b259-3a1f7af9b6c7" />

**Comment by adevra** [comment]
Hello @IvanMurzak 
I think there's still a small install-time gap worth flagging here even though the menu based fix you described works once you can reach it.

What I observed

  After install-plugin, my Assets/Plugins/NuGet/ still contained the old   
  DLLs from before the upgrade:

  Assets/Plugins/NuGet/com.IvanMurzak.ReflectorNet.5.0.0/
  Assets/Plugins/NuGet/com.IvanMurzak.McpPlugin.6.1.0/
  Assets/Plugins/NuGet/com.IvanMurzak.McpPlugin.Common.6.1.0/

  …while the freshly-installed NuGetConfig.cs in Library/PackageCache/com.i
  vanmurzak.unity.mcp@.../Editor/DependencyResolver/NuGetConfig.cs pins:   

  com.IvanMurzak.ReflectorNet            5.1.1
  com.IvanMurzak.McpPlugin               6.1.1
  com.IvanMurzak.McpPlugin.Common        6.1.1

  So the new plugin source compiles against types (ViewQuery) that don't   
  exist in the still-resident 5.0.0 DLL → the six CS0246 errors above.     

  Force Resolve NuGet DLLs would happily fix this but in my case Unity   
  dropped into Safe Mode after the failed compile, no user assemblies      
  Tools menu wasn't there. Catch-22 for anyone who doesn't already know what's
   wrong.

  **Manual recovery (in case anyone else lands here)**

  If you can't reach the Force Resolve menu, you can swap the DLLs by hand:   

  1. Read the pinned versions from Library/PackageCache/com.ivanmurzak.unity.m
  cp@.../Editor/DependencyResolver/NuGetConfig.cs.
  2. For each, curl -O https://api.nuget.org/v3-flatcontainer/<lowercase-id>/<
  version>/<lowercase-id>.<version>.nupkg, unzip, take
  lib/netstandard2.1/*.dll.
  3. For each Assets/Plugins/NuGet/<id>.<old>/: make <id>.<new>/, drop the new
   DLL in, copy the old .dll.meta over verbatim so the GUID is preserved, then
   delete the old folder + its sibling .meta.
  4. Refocus Unity. Compile succeeds, plugin loads, Force Resolve menu        
  reappears.


  Possible upstream fix

  It might be worth having unity-mcp-cli install-plugin invoke the package    
  restorer as the last step of the upgrade flow, so Assets/Plugins/NuGet/     
  always tracks the new NuGetConfig.cs before the user reopens Unity. That    
  would close the window where a user can hit a broken-compile state on first 
  launch after upgrade, which is what makes Safe Mode reachable.
  Alternatively, a tiny isolated InitializeOnLoad-level mismatch check (in an 
  assembly with no other plugin dependencies) could run Restore before the    
  broken assemblies even attempt to compile.

**Comment by NewbNinja** [comment]
Yeah I did "Force Resolve" but it didn't change anything sadly.  Is there a fix for this, or can I roll back to a version that worked?

**Comment by IvanMurzak** [comment]
> Yeah I did "Force Resolve" but it didn't change anything sadly. Is there a fix for this, or can I roll back to a version that worked?

Please try to restart Unity Editor, it will prompt this popup `Enter Safe Mode?` - choose `Ignore`

<img width="858" height="451" alt="Image" src="https://github.com/user-attachments/assets/158b2e00-4ab3-4ea8-8aee-a657be68262a" />

**Comment by NewbNinja** [comment]
> > Yeah I did "Force Resolve" but it didn't change anything sadly. Is there a fix for this, or can I roll back to a version that worked?
> 
> Please try to restart Unity Editor, it will prompt this popup `Enter Safe Mode?` - choose `Ignore`
> 
> <img alt="Image" width="858" height="451" src="https://private-user-images.githubusercontent.com/9135028/586191012-158b2e00-4ab3-4ea8-8aee-a657be68262a.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzc2Mjc2MDYsIm5iZiI6MTc3NzYyNzMwNiwicGF0aCI6Ii85MTM1MDI4LzU4NjE5MTAxMi0xNThiMmUwMC00YWIzLTRlYTgtOGFlZS1hNjU3YmU2ODI2MmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI2MDUwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNjA1MDFUMDkyMTQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODkzMTQ4NWMxNzkyNjQzNGVkNGM0OGZhNmQxZGE0NDMxMzVjMjIyYzk4ZjQzNjgwOGEzMjBhMmNmY2Q1ZDAwYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmcmVzcG9uc2UtY29udGVudC10eXBlPWltYWdlJTJGcG5nIn0.sVSOnOLqh2S2cPgrWwAAhh7IulkoeQZ6cIA9qOi2tVU">

Ahhh you updated it, appreciate you. Thanks a million
