### ISSUE TITLE
Compilation errors after upgrading to 0.68.0

### ISSUE THREAD

**Issue by Zhuwenqian** [IvanMurzak/Unity-MCP#719]
Library\PackageCache\com.ivanmurzak.unity.mcp@0.68.0\Editor\Scripts\API\Tool\Assets.Shader.GetData.cs(66,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@0.68.0\Editor\Scripts\API\Tool\Assets.GetData.cs(55,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@0.68.0\Editor\Scripts\API\Tool\Object.GetData.cs(55,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@0.68.0\Editor\Scripts\API\Tool\GameObject.Component.Get.pre-Unity.6.5.cs(65,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@0.68.0\Editor\Scripts\API\Tool\GameObject.Find.cs(68,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp@0.68.0\Editor\Scripts\API\Tool\Scene.GetData.cs(60,13): error CS0246: The type or namespace name 'ViewQuery' could not be found (are you missing a using directive or an assembly reference?)

Unity 2022.3.62f1c1

Have you given up support for the Unity 2022. X series？

**Comment by Zhuwenqian** [comment]
(Chinese users must use Tuanjie Engine or versions up to Unity 2022)

**Comment by IvanMurzak** [comment]
You may need to restart Unity (Tuanjie) Editor and the error will be gone.
If you have installed extensions - you would need to update them to the latest version.
