### ISSUE TITLE
Need a way to make this work on Unity 2021.3

### ISSUE THREAD

**Issue by simulanis-dev-yokesh-j** [IvanMurzak/Unity-MCP#105]
I have few huge project on 2021.3 and most the task in these are basic and I was able automate it but I have done on 2022.3 on a dummy project, when i tried to implement this 2021.3 there was only one issue I can find on the library which is 

`Library\PackageCache\PACKAGE_NAME\Editor\Scripts\UI\Window\MainWindowEditor.CreateGUI.cs(41,47): error CS0246: The type or namespace name 'EnumField' could not be found (are you missing a using directive or an assembly reference?)`

Currently upgrading these project is impossible for me so I want to figure out if there is way of make this plugin work with unity 2021.3!

**Comment by IvanMurzak** [comment]
I afraid it won't be easy. At least because of different UI Elements implementation in that Unity version. UI Elements are used for making the "AI Connector" window. At the start of the project I limited the minimal Unity version by `2022.3`.

But, the "AI Connector" is the only blocker. If you like to contribute into the project you may replace the window with something else, maybe UGUI or with a different UI Elements API for older Unity versions. I would appreciate it.

The related C# classes are located right here
```
Assets/Editor/Scripts/UI
```

**Comment by simulanis-dev-yokesh-j** [comment]
We have upgraded our core project it went smoother than imagined, I have been developing 2 tool since last few days, creating a different issue to discuss this!
