### ISSUE TITLE
Version compatibility regression: com.ivanmurzak.unity.mcp.probuilder@1.0.59 fails with com.ivanmurzak.unity.mcp@0.65.0

### ISSUE THREAD

**Issue by Sttrevens** [IvanMurzak/Unity-MCP#663]
### Summary
com.ivanmurzak.unity.mcp.probuilder@1.0.59 appears incompatible with com.ivanmurzak.unity.mcp@0.65.0.

When upgrading MCP to 0.65.0, Unity compilation fails with missing-type errors (e.g. McpPluginToolAttribute, Title, ReadOnlyHint).

### Environment
- Unity 2022.3.34f1
- com.ivanmurzak.unity.mcp = 0.65.0
- com.ivanmurzak.unity.mcp.probuilder = 1.0.59

### Repro Steps
1. Install com.ivanmurzak.unity.mcp@0.65.0
2. Install com.ivanmurzak.unity.mcp.probuilder@1.0.59
3. Open project / trigger script compilation

### Actual
Compilation fails with multiple CS0234 / CS0246 errors due to unresolved types.

### Expected
Project compiles successfully, or package manager prevents selecting incompatible versions.

### Workaround
Downgrade MCP to 0.63.1; compilation recovers.

### Suggestion
- Release a mcp.probuilder version compatible with MCP 0.65.0, or
- tighten dependency/version constraints so incompatible combinations cannot be installed.

**Comment by IvanMurzak** [comment]
Thanks for the report @Sttrevens 
What exact compilation errors do you have? Please share.

**Comment by IvanMurzak** [comment]
@Sttrevens you would need to upgrade the `Unity-AI-ProBuilder` package. It was updated to support the changes.
