### ISSUE TITLE
Particle System Extension Gives Error After 0.68.0 Update

### ISSUE THREAD

**Issue by vaulcul** [IvanMurzak/Unity-MCP#717]
After updating to 0.68.0 the Particle System Extension is broken and gives the following errors (I have uninstalled and re-installed the Extension multiple times, no problems when gone, lots of problems when present):

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\GetParticleSystemResponse.cs(14,40): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'com.IvanMurzak.Unity.MCP.Runtime' (are you missing an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\ModifyParticleSystemResponse.cs(13,40): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'com.IvanMurzak.Unity.MCP.Runtime' (are you missing an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\ParticleSystemData.cs(14,40): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'com.IvanMurzak.Unity.MCP.Runtime' (are you missing an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Tools\ParticleSystem.Get.cs(16,40): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'com.IvanMurzak.Unity.MCP.Runtime' (are you missing an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Tools\ParticleSystem.Modify.cs(20,40): error CS0234: The type or namespace name 'Data' does not exist in the namespace 'com.IvanMurzak.Unity.MCP.Runtime' (are you missing an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\GetParticleSystemResponse.cs(25,16): error CS0246: The type or namespace name 'GameObjectRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\ModifyParticleSystemResponse.cs(27,16): error CS0246: The type or namespace name 'GameObjectRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\ParticleSystemData.cs(27,16): error CS0246: The type or namespace name 'GameObjectRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\ModifyParticleSystemResponse.cs(30,16): error CS0246: The type or namespace name 'ComponentRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\ParticleSystemData.cs(30,16): error CS0246: The type or namespace name 'ComponentRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Data\GetParticleSystemResponse.cs(28,16): error CS0246: The type or namespace name 'ComponentRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Tools\ParticleSystem.Get.cs(43,13): error CS0246: The type or namespace name 'GameObjectRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Tools\ParticleSystem.Get.cs(47,13): error CS0246: The type or namespace name 'ComponentRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Tools\ParticleSystem.Modify.cs(47,13): error CS0246: The type or namespace name 'GameObjectRef' could not be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.ivanmurzak.unity.mcp.particlesystem@0dfc366e1995\Editor\Scripts\Tools\ParticleSystem.Modify.cs(51,13): error CS0246: The type or namespace name 'ComponentRef' could not be found (are you missing a using directive or an assembly reference?)

**Comment by sunzifu007** [comment]
Check the screenshot below—simply clicking the 'Update' button on the ParticleSystem should fix it. I'm not sure why, but upgrading from 0.67.3 to 0.68.0 triggered some error logs that don't go away until you manually hit that button.

<img width="200" height="420" alt="Image" src="https://github.com/user-attachments/assets/284d2d1f-41f4-4032-8711-3b4659b28237" />

**Comment by IvanMurzak** [comment]
Yes, you would need to update all the extension with the update of Unity-MCP
